#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"

if [[ -z "$@" ]]; then
  local +x ACTION="watch"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in
  watch)
    local +x CMD="process.cr specs run"
    ${=CMD} || :
    process watch "-r ./" "$CMD"
    ;;

  run)
    reset
    cd "$THIS_DIR"
    mkdir -p tmp/out
    local +x out=tmp/out/specs
    sh_color ORANGE "=== {{Compiling}} specs..."
    my_crystal __ build specs/specs.cr -o $out
    sh_color ORANGE "=== {{Running}} specs..."
    $out $@
    sh_color GREEN "=== {{DONE}} specs ==="
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

